name: Cypress tests
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 3 copies
        # of the current job in parallel
        machines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          start: yarn start
          wait-on: http://localhost:3333
        env:
          WITH_COVERAGE: true
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 1ced39be-1a3a-4fd8-b2d5-a88951d9b766
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
          name: codecov-umbrella
          # fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz
