name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 3 copies
        # of the current job in parallel
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          start: yarn start
          wait-on: http://localhost:3333
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 1ced39be-1a3a-4fd8-b2d5-a88951d9b766
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      